name: ServerBlox
author: Delocaz
main: me.Delocaz.ServerBlox.ServerBlox
version: 1.0
commands:
    sbx_home:
        aliases: [home]
    sbx_sethome:
        aliases: [sethome]
    sbx_spawn:
        aliases: [spawn]
    sbx_setspawn:
        aliases: [setspawn]
    sbx_tp:
        aliases: [tp, teleport, tele]
    spx_tp2p:
        aliases: [tp2p, t2p, p2p]